### ISSUE TITLE
Render Meta attributes with python instead of template

### ISSUE THREAD

**Issue by vstoykov** [nephila/django-meta#5]
I'm wondering if rendering of Meta objects will be better if they are rendered like widgets Media objects in Django. https://github.com/django/django/blob/master/django/forms/widgets.py#L42

This way there will be no empty new lines for missing properties. 
Also I don't think there is something to extend or change in template per project. If something need to be extended probably will be better with Python code. All HTML tags now are not in the template why we need template at all?

What you think about that?

**Comment by yakky** [comment]
We might explore this, but I feel this might end up raising the complexity of the codebase.
Any PoC available?

**Comment by DmitryFillo** [comment]
Why widgets (forms) are rendering in python? I think because form rendering is tricky. Typical form consists of any number of fields (input, select, textarea, option, etc) and fields has many customizeable attributes. Using templates for form rendering is very hard way: we must be able to add/setup attributes like size, class, title, required, sometimes we need label, sometimes not, etc. It's highly customizeable. What can template render? Only ```<select{% attrs %}>``` or something like this and encumber developer by additional actions like includes?  And that's why templates not using for widgets/media (not only in django forms).

On the one side this is not necessary for django-meta, because it's small app, all rendering can simply be done in one template. Yes, it have many if-else, but no customizing is needed for meta tags, no any additional attrs, etc.

On the other side template does nothing and it's not really needed. Moreover, all rendering actually made by templatetags and only if-else done by templates. It seems not beautiful, but very simple: we able to use context in the templates, substitute/extend/inlcude meta.html, etc.

What conclusions?

I think django-meta will works well enough with current implementation and it is unlikely that templates will be hard to use. Also django-meta covers all common meta tags and they will not become more customizeable in the future I guess. Django-meta now seems like typical django view with forming context and rendering it in the templates. It simply, works, but not perfect because template rendering is not really needed.

Rendering meta tags like the way in the forms/widgets will be perfect, we can implement class-based meta tags configuration (like forms), but it seems like overkill, I don't see any real PoC. Meta tags seems like a single entity, not a constructor like forms.

By the way, empty lines are normal for html, it can be fixed with [spaceless](https://docs.djangoproject.com/en/1.8/ref/templates/builtins/#spaceless) or [django-htmlmin](https://github.com/cobrateam/django-htmlmin).

**Comment by yakky** [comment]
Closing this. I think that rendering content in a template provides the best tradeoff between simplicity, speed and ease of maintenance
Thanks to @vstoykov and @DmitryFillo for the discussion
